const mongoose = require("mongoose");
const Quote = require("./models/quoteModel");
require("dotenv").config({ path: '../.env' });

mongoose
  .connect(process.env.MONGODB_CONNECTION_STRING)
  .then(() => console.log("MongoDB connected"))
  .catch((err) => console.log("MongoDB connection error", err));

  const quotes = [
    { text: "I am healing more each day and embracing my recovery journey." },
    { text: "My body is strong, resilient, and capable of amazing recovery." },
    { text: "I trust my body to heal and thrive in its own time." },
    { text: "Each day, I become healthier, stronger, and more energetic." },
    { text: "I release all negativity and welcome positive energy." },
    { text: "My mind and body are calm, relaxed, and focused on healing." },
    { text: "I am worthy of good health and wellness." },
    { text: "I am patient with myself and my recovery process." },
    { text: "I celebrate every small victory in my healing journey." },
    { text: "My body is restoring its natural balance and health." },
    { text: "I am in control of my body and its healing process." },
    { text: "I nourish my body with healthy, nutritious foods." },
    { text: "I am grateful for my body's ability to heal and recover." },
    { text: "I release all tension and embrace relaxation and peace." },
    { text: "I am stronger than any challenge that comes my way." },
    { text: "I choose to focus on positive thoughts and healing." },
    { text: "My body is healing itself perfectly and effortlessly." },
    { text: "I am full of energy and vitality." },
    { text: "I am committed to my health and well-being." },
    { text: "I trust the process of healing and recovery." },
    { text: "My body responds positively to healthy choices." },
    { text: "I am at peace with my body and its healing process." },
    { text: "I release fear and embrace confidence in my recovery." },
    { text: "I am grateful for my progress and celebrate my milestones." },
    { text: "I am in harmony with my body's natural healing process." },
    { text: "I am deserving of a healthy, happy life." },
    { text: "I embrace a healthy lifestyle with joy and enthusiasm." },
    { text: "My mind is clear, focused, and positive." },
    { text: "I am empowered to make healthy choices for myself." },
    { text: "I am worthy of feeling good and being healthy." },
    { text: "I am strong, confident, and capable of overcoming challenges." },
    { text: "I believe in my body's ability to heal and restore." },
    { text: "I am grateful for my body's strength and resilience." },
    { text: "I release all tension and embrace calmness and peace." },
    { text: "I am patient and gentle with myself during my recovery." },
    { text: "I choose to think positively and focus on healing." },
    { text: "I am constantly improving and getting better every day." },
    { text: "I am in tune with my body's needs and respond with care." },
    { text: "I am grateful for each step of my healing journey." },
    { text: "I am confident in my ability to reach my health goals." },
    { text: "I am strong, healthy, and full of vitality." },
    { text: "I am focused on my well-being and making positive changes." },
    { text: "I am surrounded by love and support in my healing journey." },
    { text: "I trust my body to guide me towards optimal health." },
    { text: "I am grateful for the healing power within me." },
    { text: "I am calm, peaceful, and relaxed as I heal." },
    { text: "I am committed to my recovery and health journey." },
    { text: "I am worthy of love, health, and happiness." },
    { text: "I am in control of my health and wellness." },
    { text: "I am grateful for the progress I make each day." },
    { text: "I am patient and kind to myself as I heal." },
    { text: "I am a powerful creator of my health and well-being." },
    { text: "I am surrounded by positive, healing energy." },
    { text: "I am in alignment with my highest health and wellness." },
    { text: "I am confident in my ability to overcome challenges." },
    { text: "I am deserving of a healthy, vibrant life." },
    { text: "I am grateful for the support and love around me." },
    { text: "I am focused on my recovery and making progress." },
    { text: "I am at peace with my healing journey." },
    { text: "I am grateful for every step of my progress." },
    { text: "I am a positive thinker and a healthy doer." },
    { text: "I am resilient and can handle anything that comes my way." },
    { text: "I am in tune with my body's natural healing process." },
    { text: "I am grateful for the opportunity to improve my health." },
    { text: "I am surrounded by healing energy and love." },
    { text: "I am confident in my body's ability to heal." },
    { text: "I am committed to a healthy, happy lifestyle." },
    { text: "I am worthy of feeling good and being healthy." },
    { text: "I am grateful for the small victories in my journey." },
    { text: "I am patient with myself and trust the healing process." },
    { text: "I am in control of my thoughts and focus on positivity." },
    { text: "I am grateful for the strength and resilience I possess." },
    { text: "I am a source of healing and positive energy." },
    { text: "I am confident in my ability to achieve my health goals." },
    { text: "I am grateful for the progress I make each day." },
    { text: "I am focused on my well-being and making positive changes." },
    { text: "I am surrounded by love and support in my journey." },
    { text: "I am grateful for the healing power within me." },
    { text: "I am calm, peaceful, and relaxed as I heal." },
    { text: "I am committed to my recovery and health journey." },
    { text: "I am worthy of love, health, and happiness." },
    { text: "I am in control of my health and wellness." },
    { text: "I am grateful for the progress I make each day." },
    { text: "I am patient and kind to myself as I heal." },
    { text: "I am a powerful creator of my health and well-being." },
    { text: "I am surrounded by positive, healing energy." },
    { text: "I am in alignment with my highest health and wellness." },
    { text: "I am grateful for the strength and resilience of my body." },
    { text: "I am committed to making healthy choices every day." },
    { text: "I am confident in my ability to overcome challenges." },
    { text: "I am deserving of a healthy, vibrant life." },
    { text: "I am grateful for the support and love around me." },
    { text: "I am focused on my recovery and making progress." },
    { text: "I am grateful for every step of my progress." },
    { text: "I am a positive thinker and a healthy doer." },
    { text: "I am resilient and can handle anything that comes my way." },
    { text: "I am in tune with my body's natural healing process." },
    { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
    { text: "Wellness is the complete integration of body, mind, and spirit.", author: "Greg Anderson" },
    { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
    { text: "Fitness is not about being better than someone else. It's about being better than you used to be.", author: "Zig Ziglar" },
    { text: "A healthy outside starts from the inside.", author: "Robert Urich" },
    { text: "Your body can stand almost anything. It's your mind that you have to convince.", author: "Unknown" },
    { text: "To enjoy the glow of good health, you must exercise.", author: "Gene Tunney" },
    { text: "The best project you'll ever work on is you.", author: "Unknown" },
    { text: "The groundwork for all happiness is good health.", author: "Leigh Hunt" },
    { text: "Health is a state of body. Wellness is a state of being.", author: "J. Stanford" },
    { text: "Don't stop when you're tired. Stop when you're done.", author: "David Goggins" },
    { text: "The first wealth is health.", author: "Ralph Waldo Emerson" },
    { text: "The human body is the best picture of the human soul.", author: "Ludwig Wittgenstein" },
    { text: "He who has health has hope, and he who has hope has everything.", author: "Arabian Proverb" },
    { text: "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier.", author: "Tom Stoppard" },
    { text: "It is health that is real wealth and not pieces of gold and silver.", author: "Mahatma Gandhi" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston S. Churchill" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
    { text: "Your present circumstances don’t determine where you can go; they merely determine where you start.", author: "Nido Qubein" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" }
  ];

const seedDB = async () => {
  await Quote.deleteMany({});
  await Quote.insertMany(quotes);
  console.log("Database Seeded! ");
  mongoose.connection.close();
};

seedDB();
